version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_DEBUG=true
      - APP_POSTGRES_HOST=db
      - APP_POSTGRES_DB=app
      - APP_POSTGRES_USER=app
      - APP_POSTGRES_PASSWORD=app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge